package config

import (
	"time"

	"github.com/FernasFragas/Nandocode/internal/llm"
	"github.com/FernasFragas/Nandocode/internal/permissions"
	"github.com/FernasFragas/Nandocode/internal/semantic"
)

func DefaultConfig() Config {
	return Config{
		DefaultModel:                       llm.DefaultModel,
		OllamaBaseURL:                      "http://localhost:11434",
		OllamaCloudEnabled:                 true,
		ChatKeepAlive:                      "5m",
		LLMStreamIdleTimeout:               90 * time.Second,
		CloudLLMStreamIdleTimeout:          5 * time.Minute,
		PermissionMode:                     permissions.ModeDefault,
		MaxTurns:                           200,
		MaxConcurrentTools:                 10,
		BashTimeout:                        5 * time.Minute,
		MaxReadChars:                       65536,
		MaxResultChars:                     8192,
		MaxDirFiles:                        200,
		MaxPromptFiles:                     400,
		MaxDirBytes:                        512 * 1024,
		MaxPromptBytes:                     2 * 1024 * 1024,
		MaxDirDepth:                        8,
		MentionDirectorySource:             "auto",
		MentionIncludeGitignoredOnExplicit: true,
		PromptDumpMode:                     "off",
		PromptDumpKeep:                     10,
		PromptPreviewChars:                 600,
		LogLevel:                           "info",
		LogFormat:                          "text",
		SlowStageNoticeThreshold:           750 * time.Millisecond,
		ContextMode:                        "auto",
		MemoryRecallMode:                   "fast",
		MemoryEnabled:                      true,
		SemanticIndex:                      semantic.DefaultConfig(),
	}
}

func DefaultConfigTOML() string {
	return `# nandocodego configuration
# Generated by "nandocodego init"

	# default_model = "qwen3.6:35b"
# ollama_base_url = "http://localhost:11434"
# ollama_cloud_enabled = true
# chat_keep_alive = "5m"
# llm_stream_idle_timeout = "90s"
# cloud_llm_stream_idle_timeout = "5m"
# permission_mode = "default"
# max_turns = 200
# [concurrency]
# max_batch_size = 10
# bash_timeout = "5m"
# max_read_chars = 65536
# max_result_chars = 8192
# max_dir_files = 200
# max_prompt_files = 400
# max_dir_bytes = 524288
# max_prompt_bytes = 2097152
# max_dir_depth = 8
# mention_directory_source = "auto"
# mention_include_gitignored_on_explicit = true
# prompt_dump_mode = "off"
# prompt_dump_keep = 10
# prompt_preview_chars = 600
# log_level = "info"
# log_format = "text"
# slow_stage_notice_threshold = "750ms"
# context_mode = "auto"
# memory_recall_mode = "fast"
# memory_enabled = true
# [semantic_index]
# enabled = true
# mode = "auto" # off | explicit | auto
# auto_build = false
# model = "qwen3-embedding:8b"
# dimensions = 1024
# max_chunk_tokens = 700
# chunk_overlap_tokens = 120
# max_file_bytes = 1048576
# max_records = 200000
# batch_size = 32
# top_k_records = 40
# top_k_files = 12
# max_context_bytes = 262144
# light_top_k_records = 4
# light_top_k_files = 1
# light_max_context_bytes = 8192
# light_deadline_ms = 1200
# full_top_k_records = 12
# full_top_k_files = 4
# full_max_context_bytes = 65536
# full_deadline_ms = 3000
# deep_top_k_records = 40
# deep_top_k_files = 12
# deep_max_context_bytes = 262144
# deep_deadline_ms = 3000
# hybrid_lexical_weight = 0.20
# frecency_weight = 0.10
# prompt_refresh_max_files = 8
# prompt_refresh_timeout_ms = 1500
# keep_alive = "10m"
# query_keep_alive = "30s"
# build_keep_alive = "10m"
# store_previews = true
`
}
